### ISSUE TITLE
Datos de los 7 años Faltantes - 2do Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#10]
Hola @mazf88 
Por Favor Subir Enlace del Documento donde se encuentren estos Datos.
Tanto como por Institucion como por Estudiante.
**Recuerda Trabajarlo de Sabado a Domingo**

**Comment by mazf88** [comment]
ftp://ftp.icfes.gov.co/SABER11/SB11-BASES%20DE%20DATOS/

De esta url se descargan los .zip y se suben al drive compartido por David.
