### ISSUE TITLE
Primera Version de la BD- 2do Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#11]
Hola Equipo @alexsabsan @AbabiPino @Tellez7 @melissapena , despues de la Clasificacion de los Datos, su labor es Integrar esta Informacion en la Primera Version de la Base de Datos. 
**Recuerden Trabajarlo de Miercoles a Sabado.**

**Comment by alexsabsan** [comment]
Se realiza el cargue de la versión 2 del moldeamiento de entidades 

Modelo relacional V02.txt

[Modelo relacional V02.xlsx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1774707/Modelo.relacional.V02.xlsx)

**Comment by Thorgan69** [comment]
Todos se comprometen a Subir los años para la noche del sábado, dado que los archivos no están depurados, y adicionalmente la Carga de Datos es de un volumen muy Grande .

**Comment by alexsabsan** [comment]
Se realiza carga de la relación de la primera Base de datos 

![relacion bd v002](https://user-images.githubusercontent.com/25808662/36937249-79319e48-1ede-11e8-91ab-22547f87f998.jpg)
