### ISSUE TITLE
Clasificar Datos - 2do Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#12]
Hola Equipo de Desarrollo @MichaelRL1 e @IvanMacias , 

Favor Clasificar y consolidar los datos enviados por Alex.

**Recuerden Trabajar esto de Domingo a Miercoles.**

**Comment by MichaelRodL** [comment]
Adjunto link del Excel con los resultados de las pruebas saber 11º  por estudiante, se encuentran clasificados por años de presentación.
observaciones: se realizan tablas dinámicas con los promedios de física y matemáticas de los años 2005, 2008 y 2011 esos resultados evidencian que la mayor concentración de los promedios no varia mucho entre los años, en un rango de 40 a 50.
https://drive.google.com/file/d/1pNtRDdqERwlTKl03dOAbTeSuGUkU7xk0/view?usp=sharing

**Comment by Felipepadilla1** [comment]
Adjunto link de los exceles en las cuales se hizo la depuración de los datos de los años 2009 y 2010 como se acordo en clase con los campos para cargar a la base de dato.
https://drive.google.com/drive/folders/1OgrNc1sv7ptdA7EW_pTRdqy3Rp9roXhT

**Comment by IvanMacias** [comment]
Link de excel correspondiente al icfes del año 2013
https://drive.google.com/open?id=1tmcNwaFeT2z0kSb21eJpTeq6SEa5l_xA
