### ISSUE TITLE
Diseño de Mockups FrontEnd - 2do Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#13]
@dianalis , Hola Diana , Favor Subir bosquejos o Imagenes que muestren el Diseño Visual del Frontend.
Recuerda Trabajar esto de Sabado a Lunes

**Comment by Thorgan69** [comment]
https://github.com/ISWPOLI/PracticAplicada2018I/files/1777048/mockup_parte1.pdf

**Comment by dianalis** [comment]
[mockup_parte2.pdf](https://github.com/ISWPOLI/PracticAplicada2018I/files/1777577/mockup_parte2.pdf)
