### ISSUE TITLE
Mockups y Frontend - 2do Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#14]
Hola Equipo
@dianalis , @Felipepadilla1 , @mazf88 
Trabajar en los Mockups del Proyecto .
**Recuerden Trabajar esto desde el lunes hasta el Sabado.**

**Comment by dianalis** [comment]
[mockup_parte1.pdf](https://github.com/ISWPOLI/PracticAplicada2018I/files/1777048/mockup_parte1.pdf)
Buenas noches,

Adjunto primera parte de Mockups.
