### ISSUE TITLE
Carga de BD - MySQL - 3er Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#18]
@alexsabsan @Tellez7 , Buenas tardes Chicos, por favor subir y Cargar la BD  en MySQL.

**Comment by Tellez7** [comment]
Se adjunta diagrama de entidades y su respectiva carga de datos
![resultados icfes diagrama](https://user-images.githubusercontent.com/26829809/37115940-ae66f146-221a-11e8-9047-469e8d645e24.png)
![carga datos](https://user-images.githubusercontent.com/26829809/37116057-096de298-221b-11e8-932c-f1d40df65466.png)
