### ISSUE TITLE
Algoritmo primera Ecuacion - 3er Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#19]
@MichaelRL1 @IvanMacias , Favor trabajar y documentar las investigaciones y practicas con la primera Ecuacion del Algoritmo.

**Comment by MichaelRodL** [comment]
Adjunto documento con la explicación de la primera ecuación que nos plantea el proyecto, igualmente un Excel donde se encuentran tablas y datos donde se evidencian la variación anual de los resultados de las pruebas icfes
**Excel con tablas y datos de prueba**
[datos de ecuacion.xlsx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1795011/datos.de.ecuacion.xlsx)
**Documento con explicación de la ecuación # 1**
[explicacion primera ecuacion.docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1795014/explicacion.primera.ecuacion.docx)

**Comment by IvanMacias** [comment]
Adjunto envió Excel con el procedimiento de la segunda ecuación
[Segunda ecuacion.xlsx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1799050/Segunda.ecuacion.xlsx)
