### ISSUE TITLE
Algoritmo segunda Ecuacion - 3er Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#20]
@MichaelRL1 @IvanMacias , Favor trabajar y documentar las investigaciones y practicas con la primera Ecuacion del Algoritmo.

**Comment by IvanMacias** [comment]
[Informe  Area de Desarrollo.pptx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1799054/Informe.Area.de.Desarrollo.pptx)
[Segunda ecuacion.xlsx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1799055/Segunda.ecuacion.xlsx)
Se adjunta informe diapositivas del área de desarrollo y Excel de la segunda ecuacion
