### ISSUE TITLE
Requerimientos - 4to Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#21]
@Felipepadilla1

**Comment by mazf88** [comment]
[Proyecto Practica Aplicada PruebasSaberApp.docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1799570/Proyecto.Practica.Aplicada.PruebasSaberApp.docx)


Se adjunta documento con RF,RN,RNF,CU,Diagramas Arquitectura, CU.  Documento trabajado con Felipe Padilla.

**Comment by dianalis** [comment]
[Proyecto.Practica.Aplicada.PruebasSaberApp.docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1887654/Proyecto.Practica.Aplicada.PruebasSaberApp.docx)

Se adjunta documento actualizado con diagramas
