### ISSUE TITLE
3 Ecuacion del Algoritmo - Cuarto Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#22]
@MichaelRL1 @IvanMacias

**Comment by MichaelRodL** [comment]
Adjunto presentación
[ecuaciones.pptx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1821176/ecuaciones.pptx)
 con la documentación de las 4 primeras ecuaciones presentadas en clase
