### ISSUE TITLE
Documentacion - 4to Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#24]
@melissapena @mazf88 @AbabiPino

**Comment by AbabiPino** [comment]
Por Favor Asignar esta tarea tambien a mi muchas gracias!

**Comment by melissapena** [comment]
Se deja el documento Plan de Pruebas en el drive
https://drive.google.com/drive/folders/16ZIoqTFyLxQ2ZNJwHbbF965XjJ_4an3j

**Comment by Thorgan69** [comment]
https://drive.google.com/drive/folders/16ZIoqTFyLxQ2ZNJwHbbF965XjJ_4an3j
en este link se encuentra la Documentacion Respectiva.
