### ISSUE TITLE
Carga -4to Sprint 

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#25]
@alexsabsan @Tellez7

**Comment by Tellez7** [comment]
Se adjunta archivo .sql, que contiene datos 2005 - 2006. Este archivo se estará actualizando a medida que se sigan cargando datos
[2005 - 2006.zip](https://github.com/ISWPOLI/PracticAplicada2018I/files/1834988/2005.-.2006.zip)
