### ISSUE TITLE
Ecuacion 5 - 5to Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#29]
@IvanMacias @AbabiPino @Felipepadilla1

**Comment by IvanMacias** [comment]
[Ecuacion 5.xlsx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1844893/Ecuacion.5.xlsx)
Este seria el ejemplo del desarrollo de la ecuación 5, faltaría manejar un lenguaje mas técnico y detallado, logrando tener en cuenta el complemento que se realice con la parte de probabilidad.
