### ISSUE TITLE
Revision de Escalas de Calificacion - 1er Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#3]
@Felipepadilla1 Y @mazf88 Favor subir reporte de la Revision de las Escalas de Calificacion. 
Ejemplo: ¿que fuentes usaron? y ¿porque?.

**Comment by Felipepadilla1** [comment]
Adjunto word con las escalas de calificación que se utilizan en las pruebas saber 11 por asignatura y viendo que competencia tiene en cada nivel de la misma
[Informe practica aplicada.docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1749339/Informe.practica.aplicada.docx)

**Comment by mazf88** [comment]
Adjunto word con las escalas de calificación a nivel general.
[Revisión escalas calificación.docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1749469/Revision.escalas.calificacion.docx)
