### ISSUE TITLE
Carga total de Datos - 5to Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#31]
@Tellez7 @alexsabsan

**Comment by Tellez7** [comment]
[Datos.zip](https://github.com/ISWPOLI/PracticAplicada2018I/files/1904826/Datos.zip)
Se adjunta archivo .sql el cual contiene datos 2005 - 2011. Queda pendiente a pequeñas modificaciones
