### ISSUE TITLE
Requerimientos - Sprint 7

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#32]
@dianalis , Favor subir los Requerimientos.

**Comment by dianalis** [comment]
se adjuntan requerimientos actualizados

[Proyecto.Practica.Aplicada.PruebasSaberApp.docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1901141/Proyecto.Practica.Aplicada.PruebasSaberApp.docx)
