### ISSUE TITLE
Depuracion Datos - Sprint 7

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#34]
2012-1(Esteban)/2012-2 (Santiago)
2013-1(Iván)/2013-2 (Diana)
2014-1(Melissa)/2014-2 (Santiago)
2015-1(Miguel)/2015-2 (Jesús)
 
@Tellez7 ,@IvanMacias, @dianalis, @melissapena, @Thorgan69, @mazf88 , @AbabiPino

**Comment by IvanMacias** [comment]
[SB11-20131-RGSTRO-CLFCCN-V1-0 con datos depurados.xlsx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1900978/SB11-20131-RGSTRO-CLFCCN-V1-0.con.datos.depurados.xlsx)
Archivo depurado del 2013 1

**Comment by dianalis** [comment]
Buenas noches,
Se adjunta archivo 2013-2 depurado al drive en la siguiente ruta:

https://drive.google.com/drive/folders/1OgrNc1sv7ptdA7EW_pTRdqy3Rp9roXhT

con el nombre: 
SB11-20132-RGSTRO-CLFCCN-V1-1

**Comment by melissapena** [comment]
Se depura el archivo del año 2014-1 y se deja en Drive en la carpeta de Excel Modificados

**Comment by AbabiPino** [comment]
se depuro el documento de excel 2015-2 esta en el drive en la carpeta de excel modificados

**Comment by Tellez7** [comment]
Años 2012 depurados, cambios guardados en la carpeta actual

**Comment by alexsabsan** [comment]
Se anexa consolidado Datos depurados 2005 hasta el 2010-1 

https://drive.google.com/drive/folders/1vIh03qSAyNO-0XJNgqtBsAARo75ODX2Z
