### ISSUE TITLE
Desarrollo 4 Ecuación - Sprint 7

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#35]
@MichaelRL1 , @Felipepadilla1
Favor hacer el Desarrollo de la ecuacion 4

**Comment by MichaelRodL** [comment]
Adjunto proyecto realizado en eclipse con el desarrollo de las ecuaciones 1,2,3,4 realizadas con Felipe 
en el proyecto se encuentran las clases
**-conexionMySql
-PuntajesAreas
-Ecuaciones
-pruebas**

Dentro del proyecto en la carpeta **doc** se encuentra el proyecto documentado en javadoc, para ver la documentación ingresar al archivo llamado **index**.
[Proyecto.zip](https://github.com/ISWPOLI/PracticAplicada2018I/files/1904434/Proyecto.zip)
