### ISSUE TITLE
Set de Pruebas - Sprint 7 y Sprint 8

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#36]
@AbabiPino , @melissapena , @Tellez7 , @alexsabsan 

Realizar set de pruebas y pruebas de bases de datos con las ecuaciones 1 y 2.

**Comment by melissapena** [comment]
Se deja el documento Plan de Pruebas en el drive
https://drive.google.com/drive/folders/16ZIoqTFyLxQ2ZNJwHbbF965XjJ_4an3j
