### ISSUE TITLE
Integracion Maps - Sprint 7

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#39]
Integración Api maps con plataforma web 
@mazf88 , @alexsabsan

**Comment by mazf88** [comment]
Junto a Melissa y David se realiza integración con API maps de google haciendo uso de las librerias:
BigQuery API	
 Cloud Source Repositories API	
 Google Cloud APIs	
 Google Cloud Datastore API	
 Google Cloud SQL	
 Google Cloud Storage		
 Google Cloud Storage JSON API		
 Google Maps Geocoding API		 
 Google Maps JavaScript API		 
 Google Places API Web Service		 
 Stackdriver Debugger API		
 Stackdriver Logging API		
 Stackdriver Monitoring API	
 Stackdriver Trace API

Lo anterior se puede evidenciar en la url https://github.com/ISWPOLI/PracticAplicada2018I.git

Adicionalmente, falta integrar en la etiqueta de cada municipio el valor promedio para los resultados de las pruebas saber.

**Comment by mazf88** [comment]
Se cierra Issue se seguirá trabajando la integración final durante los siguientes sprint.
