### ISSUE TITLE
Limpieza de Datos - 1er Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#4]
@MichaelRL1 e @IvanMacias , Favor Subir Reporte del Como hicieron la Limpieza de los datos.

**Comment by MichaelRodL** [comment]
Adjunto archivo Excel con los resultados de las pruebas saber   limpiados y clasificados por años de presentación.
**Resultados   prueba saber 11º  2013
Resultados prueba saber   11º  2014
Resultados prueba saber   11º  2012
Resultados prueba saber   11º  2011**

Queda pendiente revisar algunos datos si son de importancia al momento de procesarlos:
**Naturaleza:** oficial, no oficial
**Jornada:** mañana, completa, tarde, noche
**Evaluados:** numero de estudiantes evaluados por institución
**Periodo:** periodo de presentación de la prueba
[Resultados  depurados.xlsx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1748696/Resultados.depurados.xlsx)
