### ISSUE TITLE
Manual de Requerimientos de SW - Sprint 8

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#44]
Manual de Requerimientos de Software , @IvanMacias

**Comment by IvanMacias** [comment]
[MANTIS MANUAL DE INSTALACION.docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1936397/MANTIS.MANUAL.DE.INSTALACION.docx)
[MANTIS MANUAL DE USO.docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1936398/MANTIS.MANUAL.DE.USO.docx)
[Repositorio manual de uso.docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1936399/Repositorio.manual.de.uso.docx)
Quedan compartidos los manuales, esta pendiente por insertar el nombre y el logo de la empresa
