### ISSUE TITLE
Informe por Area - Sprint 8 

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#48]
Diapositivas con lo hecho por sprint por cada area.

**Comment by Tellez7** [comment]
[Presentacion Bases.pptx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1952840/Presentacion.Bases.pptx)

**Comment by IvanMacias** [comment]
[Informe  Corte 2 Ivan.pptx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1959365/Informe.Corte.2.Ivan.pptx)

**Comment by melissapena** [comment]
[Area de pruebas PA.pptx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1976031/Area.de.pruebas.PA.pptx)
