### ISSUE TITLE
Filtrar, Clasificar y Verificar Datos - 1er Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#5]
@alexsabsan y @Tellez7 
Chicos Favor subir Reporte de esto, y subir el archivo. para que procedamos a modelar y hacerle pruebas a los datos.

**Comment by Tellez7** [comment]
[Clasificacion - Verificacion.xlsx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1748630/Clasificacion.-.Verificacion.xlsx)
Se unificaron datos repetidos, celdas vacías y columnas innecesarias
