### ISSUE TITLE
Manuales - Sprint 9 

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#51]
Ivan

**Comment by IvanMacias** [comment]
[Manual Repositorio.docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1959335/Manual.Repositorio.docx)
[Manual de intalacion.docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1959336/Manual.de.intalacion.docx)
[Manual de uso.docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1959337/Manual.de.uso.docx)
[Manual Geoserver.docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1959338/Manual.Geoserver.docx)
Manuales con el logo actualizado e información validada y completada.
