### ISSUE TITLE
Integración de Código y BD - Sprint 9 y 10

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#52]
Equipo de desarrollo, Bases y requerimientos

**Comment by MichaelRodL** [comment]
[Proyecto.zip](https://github.com/ISWPOLI/PracticAplicada2018I/files/2011217/Proyecto.zip)
[INFORME DESARROLLO.pdf](https://github.com/ISWPOLI/PracticAplicada2018I/files/2011218/INFORME.DESARROLLO.pdf)
