### ISSUE TITLE
Modificación ecuación 3 y 4 

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#53]
Michael y Felipe

**Comment by MichaelRodL** [comment]
Se realizaron algunas modificaciones en el proyecto.
adjunto link de drive  con el proyecto, las modificaciones se trabajaran en ese mismo.
https://drive.google.com/file/d/1puzyenPFpsEO44RLFFusEMOnoxojZKM3/view?usp=sharing
