### ISSUE TITLE
Modelamiento de Datos - 1er Sprint

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#8]
@IvanMacias , @Tellez7 ,  Por favor subir Modelo o Bosquejo del Modelamiento de Datos.

**Comment by AbabiPino** [comment]
https://drive.google.com/drive/folders/16ZIoqTFyLxQ2ZNJwHbbF965XjJ_4an3j?usp=sharing

**Comment by Thorgan69** [comment]
Este Modelo se encuentra en el archivo **Identificacion de Estudiantes**
