### ISSUE TITLE
Reportes Individuales Semanales

### ISSUE THREAD

**Issue by Thorgan69** [ISWPOLI/PracticAplicada2018I#9]
**Reporte Semana 1**
[FORMATO PARA REGISTRO DE TRABAJO EN CLASE Y EXTRA-1.pdf](https://github.com/ISWPOLI/PracticAplicada2018I/files/1763852/FORMATO.PARA.REGISTRO.DE.TRABAJO.EN.CLASE.Y.EXTRA-1.pdf)
**Reporte Semana 2**
[FORMATO PARA REGISTRO DE TRABAJO EN CLASE Y EXTRA-2.pdf](https://github.com/ISWPOLI/PracticAplicada2018I/files/1763846/FORMATO.PARA.REGISTRO.DE.TRABAJO.EN.CLASE.Y.EXTRA-2.pdf)
**Reporte Semana 3**
[FORMATO PARA REGISTRO DE TRABAJO EN CLASE Y EXTRA-3.pdf](https://github.com/ISWPOLI/PracticAplicada2018I/files/1803470/FORMATO.PARA.REGISTRO.DE.TRABAJO.EN.CLASE.Y.EXTRA-3.pdf)

**Comment by IvanMacias** [comment]
[SEMANA 2.pdf](https://github.com/ISWPOLI/PracticAplicada2018I/files/1762992/SEMANA.2.pdf)
Reporte semana 2 Ivan Macias

**Comment by MichaelRodL** [comment]
Informe semana 2
[informe semana2.pdf](https://github.com/ISWPOLI/PracticAplicada2018I/files/1763775/informe.semana2.pdf)

**Comment by mazf88** [comment]
[FORMATO PARA REGISTRO DE TRABAJO EN CLASE Y EXTRA .docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1763813/FORMATO.PARA.REGISTRO.DE.TRABAJO.EN.CLASE.Y.EXTRA.docx)

Informe individual semana 2.

**Comment by Felipepadilla1** [comment]
Informe individual segunda semana
[reporte.pdf](https://github.com/ISWPOLI/PracticAplicada2018I/files/1764244/reporte.pdf)

**Comment by Tellez7** [comment]
[Formato Practica.pdf](https://github.com/ISWPOLI/PracticAplicada2018I/files/1769783/Formato.Practica.pdf)
Informe Semana 2

**Comment by Tellez7** [comment]
[Informe Semana 2.docx](https://github.com/ISWPOLI/PracticAplicada2018I/files/1769785/Informe.Semana.2.docx)
Informe Semana 2

**Comment by Tellez7** [comment]
[Informe Semana 2.pdf](https://github.com/ISWPOLI/PracticAplicada2018I/files/1769787/Informe.Semana.2.pdf)
Informe Semana 2

**Comment by dianalis** [comment]
[Reporte_Semana2.pdf](https://github.com/ISWPOLI/PracticAplicada2018I/files/1777046/Reporte_Semana2.pdf)
Buenas noches,

Adjunto reporte correspondiente a la semana 2.
